backend:
  name: github
  repo: HusamMohammed/vivereaberlino-gatsby

media_folder: content/assets
public_folder: /assets

collections:
  - name: article
    label: Article
    folder: content/article
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { Label: Image, name: thumbnail, widget: image }
      - { label: Category, name: category, widget: string }
      - { label: Difficulty, name: difficulty, widget: string }
      - { label: Location, name: location, widget: string}
      - { label: Tags, name: tags, widget: string }
      - { label: Date, name: date, widget: date }
      - { label: Body, name: body, widget: markdown }